Email Confirmation using Gmail API
rizsim214/daily-quest-app pull request #15
Opened 2022-09-07 13:01 UTC by jowseep

Hi, Riz. For your approval. Thank you. :)

2022-09-07 14:17 UTC, rizsim214 approved these changes

2022-09-07 14:35 UTC, rizsim214 requested changes
please resolve conflict on method searchAllQuestFromDB() on QuestDAO.java

2022-09-07 15:00 UTC, jowseep commented
This is noted, Riz. Will work on it.

2022-09-08 10:21 UTC, jowseep commented
Riz, I was able to resolve the conflict in searchAllQuestFromDB(). Could you please check?

2022-09-08 10:28 UTC, rizsim214 approved these changes

2022-09-08 10:28 UTC, merged